export const WFM_LOCALES = ['en', 'es', 'pt', 'fr', 'de'] as const
export type WfmLocale = (typeof WFM_LOCALES)[number]
export const DEFAULT_LOCALE: WfmLocale = 'en'
export const LANGUAGE_LABELS: Record<WfmLocale, string> = { en: 'English', es: 'Español', pt: 'Português', fr: 'Français', de: 'Deutsch' }
export const TRANSLATIONS: Record<WfmLocale, Record<string, string>> = {
  en: { Players:'Players', Scouting:'Scouting', Contracts:'Contracts', Transfers:'Transfers', Salaries:'Salaries', Clubs:'Clubs', Competitions:'Competitions', 'LIVE DATABASE':'LIVE DATABASE', 'Sign in':'Sign in', Language:'Language', Welcome:'Welcome', 'Edit profile & settings':'Edit profile & settings', 'Club workspace':'Club workspace', 'Scouting workspace':'Scouting workspace', 'Saved reports':'Saved reports', 'Sign out':'Sign out' },
  es: { Players:'Jugadoras', Scouting:'Scouting', Contracts:'Contratos', Transfers:'Transferencias', Salaries:'Salarios', Clubs:'Clubes', Competitions:'Competiciones', 'LIVE DATABASE':'BASE DE DATOS EN VIVO', 'Sign in':'Iniciar sesión', Language:'Idioma', Welcome:'Bienvenido', 'Edit profile & settings':'Editar perfil y configuración', 'Club workspace':'Espacio del club', 'Scouting workspace':'Espacio de scouting', 'Saved reports':'Informes guardados', 'Sign out':'Cerrar sesión' },
  pt: { Players:'Jogadoras', Scouting:'Scouting', Contracts:'Contratos', Transfers:'Transferências', Salaries:'Salários', Clubs:'Clubes', Competitions:'Competições', 'LIVE DATABASE':'BANCO DE DADOS AO VIVO', 'Sign in':'Entrar', Language:'Idioma', Welcome:'Bem-vindo', 'Edit profile & settings':'Editar perfil e configurações', 'Club workspace':'Espaço do clube', 'Scouting workspace':'Espaço de scouting', 'Saved reports':'Relatórios salvos', 'Sign out':'Sair' },
  fr: { Players:'Joueuses', Scouting:'Scouting', Contracts:'Contrats', Transfers:'Transferts', Salaries:'Salaires', Clubs:'Clubs', Competitions:'Compétitions', 'LIVE DATABASE':'BASE DE DONNÉES EN DIRECT', 'Sign in':'Connexion', Language:'Langue', Welcome:'Bienvenue', 'Edit profile & settings':'Modifier le profil et les paramètres', 'Club workspace':'Espace du club', 'Scouting workspace':'Espace scouting', 'Saved reports':'Rapports enregistrés', 'Sign out':'Se déconnecter' },
  de: { Players:'Spielerinnen', Scouting:'Scouting', Contracts:'Verträge', Transfers:'Transfers', Salaries:'Gehälter', Clubs:'Vereine', Competitions:'Wettbewerbe', 'LIVE DATABASE':'LIVE-DATENBANK', 'Sign in':'Anmelden', Language:'Sprache', Welcome:'Willkommen', 'Edit profile & settings':'Profil & Einstellungen', 'Club workspace':'Vereinsbereich', 'Scouting workspace':'Scouting-Bereich', 'Saved reports':'Gespeicherte Berichte', 'Sign out':'Abmelden' },
}
export function isWfmLocale(value: string | null | undefined): value is WfmLocale { return !!value && (WFM_LOCALES as readonly string[]).includes(value) }
export function getLocaleFromPathname(pathname: string): WfmLocale { const segment = pathname.split('/')[1]; return isWfmLocale(segment) ? segment : DEFAULT_LOCALE }
export function localizedPath(locale: WfmLocale, pathname: string) { const cleanPath = pathname === '/' ? '' : pathname.replace(/^\/+/, ''); return locale === DEFAULT_LOCALE ? `/${cleanPath}` : `/${locale}${cleanPath ? `/${cleanPath}` : ''}` }
export function translate(locale: WfmLocale, key: string) { return TRANSLATIONS[locale][key] ?? TRANSLATIONS[DEFAULT_LOCALE][key] ?? key }