import type { WfmLocale } from './i18n'

const EN: Record<string,string> = {
  'Loading acquisition queue…':'Loading acquisition queue…','Global acquisition queue':'Global acquisition queue','Control competition-level acquisition work before data reaches the production intelligence layer.':'Control competition-level acquisition work before data reaches the production intelligence layer.','Data Admin':'Data Admin','League Coverage':'League Coverage','Sources':'Sources','Queue updated.':'Queue updated.','Access restricted':'Access restricted','tasks':'tasks','Priority':'Priority','attempts':'attempts','evidence':'evidence','Start':'Start','Review':'Review','Complete':'Complete','Requeue':'Requeue','No acquisition tasks match the current filters.':'No acquisition tasks match the current filters.','Loading…':'Loading…','Admin access required.':'Admin access required.','Loading historical data…':'Loading historical data…','No historical data is available.':'No historical data is available.','Loading match center…':'Loading match center…','News administration':'News administration','Loading news administration…':'Loading news administration…','Loading batch…':'Loading batch…','Loading player coverage…':'Loading player coverage…','Loading competition coverage…':'Loading competition coverage…','Loading agency accounts…':'Loading agency accounts…','Agency review':'Agency review','Agency relationship review':'Agency relationship review','Approve':'Approve','Reject':'Reject','No pending agency accounts.':'No pending agency accounts.','Agency approved.':'Agency approved.','Agency rejected.':'Agency rejected.','Agency revoked.':'Agency revoked.','Queue updated':'Queue updated','Source name is required.':'Source name is required.','Publisher and RSS/Atom feed URL are required.':'Publisher and RSS/Atom feed URL are required.'
}

const ES: Record<string,string> = {
  'Loading acquisition queue…':'Cargando cola de adquisición…','Global acquisition queue':'Cola global de adquisición','Control competition-level acquisition work before data reaches the production intelligence layer.':'Controla el trabajo de adquisición a nivel de competición antes de que los datos lleguen a la capa de inteligencia de producción.','Data Admin':'Administración de datos','League Coverage':'Cobertura de ligas','Sources':'Fuentes','Queue updated.':'Cola actualizada.','Access restricted':'Acceso restringido','tasks':'tareas','Priority':'Prioridad','attempts':'intentos','evidence':'evidencia','Start':'Iniciar','Review':'Revisar','Complete':'Completar','Requeue':'Volver a poner en cola','No acquisition tasks match the current filters.':'Ninguna tarea de adquisición coincide con los filtros actuales.','Loading…':'Cargando…','Admin access required.':'Se requiere acceso de administrador.','Loading historical data…':'Cargando datos históricos…','No historical data is available.':'No hay datos históricos disponibles.','Loading match center…':'Cargando centro de partidos…','News administration':'Administración de noticias','Loading news administration…':'Cargando administración de noticias…','Loading batch…':'Cargando lote…','Loading player coverage…':'Cargando cobertura de jugadoras…','Loading competition coverage…':'Cargando cobertura de competiciones…','Loading agency accounts…':'Cargando cuentas de agencias…','Agency review':'Revisión de agencias','Agency relationship review':'Revisión de relaciones con agencias','Approve':'Aprobar','Reject':'Rechazar','No pending agency accounts.':'No hay cuentas de agencias pendientes.','Agency approved.':'Agencia aprobada.','Agency rejected.':'Agencia rechazada.','Agency revoked.':'Agencia revocada.','Queue updated':'Cola actualizada','Source name is required.':'El nombre de la fuente es obligatorio.','Publisher and RSS/Atom feed URL are required.':'El editor y la URL del feed RSS/Atom son obligatorios.'
}

const PT: Record<string,string> = {
  'Loading acquisition queue…':'Carregando fila de aquisição…','Global acquisition queue':'Fila global de aquisição','Control competition-level acquisition work before data reaches the production intelligence layer.':'Controle o trabalho de aquisição por competição antes que os dados cheguem à camada de inteligência de produção.','Data Admin':'Administração de dados','League Coverage':'Cobertura de ligas','Sources':'Fontes','Queue updated.':'Fila atualizada.','Access restricted':'Acesso restrito','tasks':'tarefas','Priority':'Prioridade','attempts':'tentativas','evidence':'evidência','Start':'Iniciar','Review':'Revisar','Complete':'Concluir','Requeue':'Recolocar na fila','No acquisition tasks match the current filters.':'Nenhuma tarefa de aquisição corresponde aos filtros atuais.','Loading…':'Carregando…','Admin access required.':'É necessário acesso de administrador.','Loading historical data…':'Carregando dados históricos…','No historical data is available.':'Não há dados históricos disponíveis.','Loading match center…':'Carregando central de partidas…','News administration':'Administração de notícias','Loading news administration…':'Carregando administração de notícias…','Loading batch…':'Carregando lote…','Loading player coverage…':'Carregando cobertura de jogadoras…','Loading competition coverage…':'Carregando cobertura de competições…','Loading agency accounts…':'Carregando contas de agências…','Agency review':'Revisão de agências','Agency relationship review':'Revisão de relações com agências','Approve':'Aprovar','Reject':'Rejeitar','No pending agency accounts.':'Não há contas de agências pendentes.','Agency approved.':'Agência aprovada.','Agency rejected.':'Agência rejeitada.','Agency revoked.':'Agência revogada.','Queue updated':'Fila atualizada','Source name is required.':'O nome da fonte é obrigatório.','Publisher and RSS/Atom feed URL are required.':'O editor e a URL do feed RSS/Atom são obrigatórios.'
}

const FR: Record<string,string> = {
  'Loading acquisition queue…':'Chargement de la file d’acquisition…','Global acquisition queue':'File globale d’acquisition','Control competition-level acquisition work before data reaches the production intelligence layer.':'Contrôlez le travail d’acquisition par compétition avant l’arrivée des données dans la couche d’intelligence de production.','Data Admin':'Administration des données','League Coverage':'Couverture des ligues','Sources':'Sources','Queue updated.':'File mise à jour.','Access restricted':'Accès restreint','tasks':'tâches','Priority':'Priorité','attempts':'tentatives','evidence':'preuves','Start':'Démarrer','Review':'Examiner','Complete':'Terminer','Requeue':'Remettre en file','No acquisition tasks match the current filters.':'Aucune tâche d’acquisition ne correspond aux filtres actuels.','Loading…':'Chargement…','Admin access required.':'Accès administrateur requis.','Loading historical data…':'Chargement des données historiques…','No historical data is available.':'Aucune donnée historique disponible.','Loading match center…':'Chargement du centre des matchs…','News administration':'Administration des actualités','Loading news administration…':'Chargement de l’administration des actualités…','Loading batch…':'Chargement du lot…','Loading player coverage…':'Chargement de la couverture des joueuses…','Loading competition coverage…':'Chargement de la couverture des compétitions…','Loading agency accounts…':'Chargement des comptes d’agences…','Agency review':'Examen des agences','Agency relationship review':'Examen des relations avec les agences','Approve':'Approuver','Reject':'Rejeter','No pending agency accounts.':'Aucun compte d’agence en attente.','Agency approved.':'Agence approuvée.','Agency rejected.':'Agence rejetée.','Agency revoked.':'Agence révoquée.','Queue updated':'File mise à jour','Source name is required.':'Le nom de la source est obligatoire.','Publisher and RSS/Atom feed URL are required.':'L’éditeur et l’URL du flux RSS/Atom sont obligatoires.'
}

const DE: Record<string,string> = {
  'Loading acquisition queue…':'Akquisitionswarteschlange wird geladen…','Global acquisition queue':'Globale Akquisitionswarteschlange','Control competition-level acquisition work before data reaches the production intelligence layer.':'Steuern Sie die Akquise auf Wettbewerbsebene, bevor Daten die Produktions-Intelligenzschicht erreichen.','Data Admin':'Datenverwaltung','League Coverage':'Ligaabdeckung','Sources':'Quellen','Queue updated.':'Warteschlange aktualisiert.','Access restricted':'Zugriff eingeschränkt','tasks':'Aufgaben','Priority':'Priorität','attempts':'Versuche','evidence':'Belege','Start':'Starten','Review':'Prüfen','Complete':'Abschließen','Requeue':'Erneut einreihen','No acquisition tasks match the current filters.':'Keine Akquisitionsaufgaben entsprechen den aktuellen Filtern.','Loading…':'Wird geladen…','Admin access required.':'Administratorzugriff erforderlich.','Loading historical data…':'Historische Daten werden geladen…','No historical data is available.':'Keine historischen Daten verfügbar.','Loading match center…':'Spielzentrale wird geladen…','News administration':'Nachrichtenverwaltung','Loading news administration…':'Nachrichtenverwaltung wird geladen…','Loading batch…':'Stapel wird geladen…','Loading player coverage…':'Spielerinnenabdeckung wird geladen…','Loading competition coverage…':'Wettbewerbsabdeckung wird geladen…','Loading agency accounts…':'Agenturkonten werden geladen…','Agency review':'Agenturprüfung','Agency relationship review':'Prüfung der Agenturbeziehungen','Approve':'Genehmigen','Reject':'Ablehnen','No pending agency accounts.':'Keine ausstehenden Agenturkonten.','Agency approved.':'Agentur genehmigt.','Agency rejected.':'Agentur abgelehnt.','Agency revoked.':'Agentur widerrufen.','Queue updated':'Warteschlange aktualisiert','Source name is required.':'Der Quellenname ist erforderlich.','Publisher and RSS/Atom feed URL are required.':'Herausgeber und RSS/Atom-Feed-URL sind erforderlich.'
}

export const WFM_DATA_TRANSLATIONS: Record<WfmLocale, Record<string,string>> = { en: EN, es: ES, pt: PT, fr: FR, de: DE }
