import type { WfmLocale } from './i18n'

const EN: Record<string,string> = {
  'Loading news administration…':'Loading news administration…','Access restricted':'Access restricted','This workspace is limited to WFM administrators.':'This workspace is limited to WFM administrators.','M17 · NEWS INGESTION':'M17 · NEWS INGESTION','News sources':'News sources','Approve RSS/Atom feeds, ingest source-linked stories, and monitor freshness. WFM stores the original source URL rather than copying publisher content.':'Approve RSS/Atom feeds, ingest source-linked stories, and monitor freshness. WFM stores the original source URL rather than copying publisher content.','Data administration':'Data administration','Homepage':'Homepage','APPROVED SOURCES':'APPROVED SOURCES','Add RSS / Atom feed':'Add RSS / Atom feed','Publisher':'Publisher','Official league / publication':'Official league / publication','Feed URL':'Feed URL','Add approved source':'Add approved source','AUTOMATION':'AUTOMATION','Ingest approved feeds':'Ingest approved feeds','Fetches active feeds, normalizes recent stories, and updates the WFM news table. No article text is republished.':'Fetches active feeds, normalizes recent stories, and updates the WFM news table. No article text is republished.','Run news ingestion now':'Run news ingestion now','FRESHNESS':'FRESHNESS','configured sources':'configured sources','Healthy':'Healthy','Stale':'Stale','Errors':'Errors','Never checked':'Never checked','Last success':'Last success','Not successfully ingested yet.':'Not successfully ingested yet.','Last error':'Last error','Health':'Health','error':'error','never checked':'never checked','stale':'stale','healthy':'healthy','active':'active','paused':'paused','Pause':'Pause','Activate':'Activate','No approved feeds yet.':'No approved feeds yet.','Publisher and RSS/Atom feed URL are required.':'Publisher and RSS/Atom feed URL are required.','Approved news source added.':'Approved news source added.','News ingestion failed.':'News ingestion failed.','News ingestion complete':'News ingestion complete','added':'added','updated':'updated','errors':'errors'
}
const ES: Record<string,string> = {
  'Loading news administration…':'Cargando administración de noticias…','Access restricted':'Acceso restringido','This workspace is limited to WFM administrators.':'Este espacio está limitado a los administradores de WFM.','M17 · NEWS INGESTION':'M17 · INGESTA DE NOTICIAS','News sources':'Fuentes de noticias','Approve RSS/Atom feeds, ingest source-linked stories, and monitor freshness. WFM stores the original source URL rather than copying publisher content.':'Aprueba feeds RSS/Atom, ingesta historias vinculadas a fuentes y controla su actualización. WFM guarda la URL original de la fuente en lugar de copiar contenido editorial.','Data administration':'Administración de datos','Homepage':'Página de inicio','APPROVED SOURCES':'FUENTES APROBADAS','Add RSS / Atom feed':'Añadir feed RSS / Atom','Publisher':'Editor','Official league / publication':'Liga / publicación oficial','Feed URL':'URL del feed','Add approved source':'Añadir fuente aprobada','AUTOMATION':'AUTOMATIZACIÓN','Ingest approved feeds':'Ingerir feeds aprobados','Fetches active feeds, normalizes recent stories, and updates the WFM news table. No article text is republished.':'Obtiene feeds activos, normaliza historias recientes y actualiza la tabla de noticias de WFM. No se republica texto de artículos.','Run news ingestion now':'Ejecutar ingesta de noticias ahora','FRESHNESS':'ACTUALIZACIÓN','configured sources':'fuentes configuradas','Healthy':'Saludable','Stale':'Desactualizada','Errors':'Errores','Never checked':'Nunca comprobada','Last success':'Último éxito','Not successfully ingested yet.':'Aún no se ha ingerido correctamente.','Last error':'Último error','Health':'Estado','error':'error','never checked':'nunca comprobada','stale':'desactualizada','healthy':'saludable','active':'activa','paused':'pausada','Pause':'Pausar','Activate':'Activar','No approved feeds yet.':'Aún no hay feeds aprobados.','Publisher and RSS/Atom feed URL are required.':'El editor y la URL del feed RSS/Atom son obligatorios.','Approved news source added.':'Fuente de noticias aprobada añadida.','News ingestion failed.':'Falló la ingesta de noticias.','News ingestion complete':'Ingesta de noticias completada','added':'añadidas','updated':'actualizadas','errors':'errores'
}
const PT: Record<string,string> = {
  ...EN,'Loading news administration…':'Carregando administração de notícias…','Access restricted':'Acesso restrito','This workspace is limited to WFM administrators.':'Este espaço é limitado aos administradores do WFM.','News sources':'Fontes de notícias','Data administration':'Administração de dados','Homepage':'Página inicial','APPROVED SOURCES':'FONTES APROVADAS','Add RSS / Atom feed':'Adicionar feed RSS / Atom','Publisher':'Editor','Official league / publication':'Liga / publicação oficial','Feed URL':'URL do feed','Add approved source':'Adicionar fonte aprovada','AUTOMATION':'AUTOMAÇÃO','Ingest approved feeds':'Ingerir feeds aprovados','Run news ingestion now':'Executar ingestão de notícias agora','FRESHNESS':'ATUALIZAÇÃO','Healthy':'Saudável','Stale':'Desatualizada','Errors':'Erros','Never checked':'Nunca verificada','Last success':'Último sucesso','Not successfully ingested yet.':'Ainda não foi ingerida com sucesso.','Last error':'Último erro','Health':'Saúde','error':'erro','never checked':'nunca verificada','stale':'desatualizada','healthy':'saudável','active':'ativa','paused':'pausada','Pause':'Pausar','Activate':'Ativar','No approved feeds yet.':'Nenhum feed aprovado ainda.','Publisher and RSS/Atom feed URL are required.':'O editor e a URL do feed RSS/Atom são obrigatórios.','Approved news source added.':'Fonte de notícias aprovada adicionada.','News ingestion failed.':'Falha na ingestão de notícias.','News ingestion complete':'Ingestão de notícias concluída','added':'adicionadas','updated':'atualizadas','errors':'erros'
}
const FR: Record<string,string> = {
  ...EN,'Loading news administration…':'Chargement de l’administration des actualités…','Access restricted':'Accès restreint','This workspace is limited to WFM administrators.':'Cet espace est réservé aux administrateurs WFM.','News sources':'Sources d’actualités','Data administration':'Administration des données','Homepage':'Accueil','APPROVED SOURCES':'SOURCES APPROUVÉES','Add RSS / Atom feed':'Ajouter un flux RSS / Atom','Publisher':'Éditeur','Official league / publication':'Ligue / publication officielle','Feed URL':'URL du flux','Add approved source':'Ajouter la source approuvée','AUTOMATION':'AUTOMATISATION','Ingest approved feeds':'Ingérer les flux approuvés','Run news ingestion now':'Lancer l’ingestion des actualités','FRESHNESS':'FRAÎCHEUR','Healthy':'Sain','Stale':'Obsolète','Errors':'Erreurs','Never checked':'Jamais vérifié','Last success':'Dernier succès','Not successfully ingested yet.':'Pas encore ingéré avec succès.','Last error':'Dernière erreur','Health':'État','error':'erreur','never checked':'jamais vérifié','stale':'obsolète','healthy':'sain','active':'actif','paused':'en pause','Pause':'Mettre en pause','Activate':'Activer','No approved feeds yet.':'Aucun flux approuvé pour le moment.','Publisher and RSS/Atom feed URL are required.':'L’éditeur et l’URL du flux RSS/Atom sont obligatoires.','Approved news source added.':'Source d’actualités approuvée ajoutée.','News ingestion failed.':'Échec de l’ingestion des actualités.','News ingestion complete':'Ingestion des actualités terminée','added':'ajoutées','updated':'mises à jour','errors':'erreurs'
}
const DE: Record<string,string> = {
  ...EN,'Loading news administration…':'Nachrichtenverwaltung wird geladen…','Access restricted':'Zugriff eingeschränkt','This workspace is limited to WFM administrators.':'Dieser Bereich ist auf WFM-Administratoren beschränkt.','News sources':'Nachrichtenquellen','Data administration':'Datenverwaltung','Homepage':'Startseite','APPROVED SOURCES':'FREIGEGEBENE QUELLEN','Add RSS / Atom feed':'RSS-/Atom-Feed hinzufügen','Publisher':'Herausgeber','Official league / publication':'Offizielle Liga / Publikation','Feed URL':'Feed-URL','Add approved source':'Freigegebene Quelle hinzufügen','AUTOMATION':'AUTOMATISIERUNG','Ingest approved feeds':'Freigegebene Feeds importieren','Run news ingestion now':'Nachrichtenimport jetzt ausführen','FRESHNESS':'AKTUALITÄT','Healthy':'Gesund','Stale':'Veraltet','Errors':'Fehler','Never checked':'Nie geprüft','Last success':'Letzter Erfolg','Not successfully ingested yet.':'Noch nicht erfolgreich importiert.','Last error':'Letzter Fehler','Health':'Status','error':'Fehler','never checked':'nie geprüft','stale':'veraltet','healthy':'gesund','active':'aktiv','paused':'pausiert','Pause':'Pausieren','Activate':'Aktivieren','No approved feeds yet.':'Noch keine freigegebenen Feeds.','Publisher and RSS/Atom feed URL are required.':'Herausgeber und RSS-/Atom-Feed-URL sind erforderlich.','Approved news source added.':'Freigegebene Nachrichtenquelle hinzugefügt.','News ingestion failed.':'Nachrichtenimport fehlgeschlagen.','News ingestion complete':'Nachrichtenimport abgeschlossen','added':'hinzugefügt','updated':'aktualisiert','errors':'Fehler'
}
export const WFM_NEWS_TRANSLATIONS: Record<WfmLocale, Record<string,string>> = { en: EN, es: ES, pt: PT, fr: FR, de: DE }
