import type { WfmLocale } from './i18n'

export const WFM_ADMIN_EXTRA_TRANSLATIONS: Record<WfmLocale, Record<string,string>> = {
  en: {
    "Loading admin workspace…":"Loading admin workspace…","Access restricted":"Access restricted","This workspace is limited to WFM administrators.":"This workspace is limited to WFM administrators.","WFM ADMIN · CLUB ACCESS":"WFM ADMIN · CLUB ACCESS","Club access requests":"Club access requests","Review requests before users receive private club workspace access.":"Review requests before users receive private club workspace access.","Verification queue":"Verification queue","Club access approved.":"Club access approved.","Club access request rejected.":"Club access request rejected.","Club":"Club","Country unavailable":"Country unavailable","requested role":"requested role","User ID":"User ID","Working…":"Working…","Approve":"Approve","Reject":"Reject","No pending club access requests.":"No pending club access requests.",
    "Loading commercial dashboard…":"Loading commercial dashboard…","WFM ADMIN · COMMERCIAL":"WFM ADMIN · COMMERCIAL","Commercial dashboard":"Commercial dashboard","Manage access plans and manually provision commercial entitlements. Billing-provider integration can be connected later without changing this access model.":"Manage access plans and manually provision commercial entitlements. Billing-provider integration can be connected later without changing this access model.","Club access":"Club access","PLANS":"PLANS","Access catalog":"Access catalog","PROVISION":"PROVISION","Assign entitlement":"Assign entitlement","Plan":"Plan","Club ID":"Club ID","Saving…":"Saving…","Entitlement assigned.":"Entitlement assigned.","Enter a user ID or club ID.":"Enter a user ID or club ID.","No commercial entitlements have been assigned.":"No commercial entitlements have been assigned.","Active":"Active","Inactive":"Inactive","Only WFM admins can create or change entitlements. Keep payment processing outside this page until a billing provider is connected.":"Only WFM admins can create or change entitlements. Keep payment processing outside this page until a billing provider is connected.",
    "Loading import review…":"Loading import review…","WFM ADMIN · DATA REVIEW":"WFM ADMIN · DATA REVIEW","Entity review":"Entity review","← Data administration":"← Data administration","INCOMING":"INCOMING","No records are waiting for review.":"No records are waiting for review.","DETAILS":"DETAILS","Match":"Match","No candidate matches yet.":"No candidate matches yet.","NEW ENTITY":"NEW ENTITY","Name":"Name","Country / nationality":"Country / nationality","Position":"Position","Date of birth":"Date of birth","Preferred foot":"Preferred foot","League / competition":"League / competition","Cancel":"Cancel","Validate player":"Validate player","Needs review":"Needs review","Select an incoming record to review its candidates.":"Select an incoming record to review its candidates.",
    "Loading provenance inventory…":"Loading provenance inventory…","Admin access required.":"Admin access required.","PHASE 9 · M7 DATA PROVENANCE":"PHASE 9 · M7 DATA PROVENANCE","Provenance & Trust":"Provenance & Trust","Linked records":"Linked records","Missing publication date":"Missing publication date","Missing access date":"Missing access date","Records missing source":"Records missing source","Traceable records":"Traceable records","All publishers":"All publishers","All levels":"All levels","Publisher":"Publisher","Reliability":"Reliability","Published":"Published","Accessed":"Accessed","Usage":"Usage","Source":"Source","Open source":"Open source","No sources match the selected filters.":"No sources match the selected filters.",
    "Loading coverage…":"Loading coverage…","PHASE 9 · DATA SCALE":"PHASE 9 · DATA SCALE","Competition Coverage":"Competition Coverage","Track league-by-league coverage targets and current WFM inventory.":"Track league-by-league coverage targets and current WFM inventory.","Tracked leagues":"Tracked leagues","Players":"Players","Clubs":"Clubs","Seasons":"Seasons","Status":"Status","All":"All","Planned":"Planned","In progress":"In progress","Complete":"Complete","Paused":"Paused","Priority":"Priority","Competition":"Competition","Country":"Country","Targets":"Targets","Current":"Current","Action":"Action","Inventory":"Inventory","Start":"Start","Activate":"Activate",
    "Loading source pipeline…":"Loading source pipeline…","M15 · SOURCE ACQUISITION":"M15 · SOURCE ACQUISITION","Source pipeline":"Source pipeline","ADD CANDIDATE":"ADD CANDIDATE","Research a new source":"Research a new source","URL":"URL","Publisher":"Publisher","Source kind":"Source kind","Geography":"Geography","Priority (1–100)":"Priority (1–100)","Access method":"Access method","Notes":"Notes","PIPELINE":"PIPELINE","Check":"Check","No sources match this status.":"No sources match this status.","League official site":"League official site","Organization":"Organization","Country / region / global":"Country / region / global","Public web / subscription / direct contact":"Public web / subscription / direct contact",
    "Loading licensing administration…":"Loading licensing administration…","Licensing requests":"Licensing requests","Review commercial access requests before issuing an executed agreement.":"Review commercial access requests before issuing an executed agreement.","Commercial access":"Commercial access","Review":"Review","No active licensing requests.":"No active licensing requests.","AGREEMENTS":"AGREEMENTS","Issuance":"Issuance",
    "Loading WFM owner access...":"Loading WFM owner access...","WOMEN’S FOOTBALL MARKET":"WOMEN’S FOOTBALL MARKET","Owner verification":"Owner verification","Owner email":"Owner email","Password":"Password","ACCESS DENIED":"ACCESS DENIED","This account is not an owner.":"This account is not an owner.","Verification dashboard":"Verification dashboard","Pending updates":"Pending updates","Pending claims":"Pending claims","Pending official verification":"Pending official verification","Official verification":"Official verification","Refresh":"Refresh","No pending official verification requests.":"No pending official verification requests.","PENDING":"PENDING","Open evidence ↗":"Open evidence ↗","Notes:":"Notes:","Approve official":"Approve official","Needs evidence":"Needs evidence","Profile updates":"Profile updates","No pending profile updates.":"No pending profile updates.","CURRENT":"CURRENT","SUBMITTED":"SUBMITTED","Profile claims":"Profile claims","No pending profile claims.":"No pending profile claims.","Enter your password":"Enter your password"
  }
}