"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";

type P={id:string;full_name:string;nationality:string|null;position:string|null;photo_url:string|null};
type I={player_id:string;season:string;league:string|null;position:string|null;minutes:number|null;appearances:number|null;goals:number|null;assists:number|null;xg:number|null;xa:number|null;chances_created:number|null;key_passes:number|null;tackles:number|null;interceptions:number|null;progressive_carries:number|null;goals_per90:number|null;assists_per90:number|null;xg_per90:number|null;xa_per90:number|null;chances_created_per90:number|null;key_passes_per90:number|null;tackles_per90:number|null;interceptions_per90:number|null;progressive_carries_per90:number|null};
type C={player_id:string;annual_salary_usd:number|null;weekly_salary_usd:number|null;end_date:string|null;status:string|null};
type V={player_id:string;market_value_usd:number|null;valuation_date:string|null};
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const fmt=(v:number|null)=>v==null?"—":v.toLocaleString("en-US",{maximumFractionDigits:2});
const p90=(v:number|null,m:number|null)=>m?v!*90/m:null;
const sum=(r:I[])=>r.reduce((a,x)=>({minutes:a.minutes+(x.minutes||0),appearances:a.appearances+(x.appearances||0),goals:a.goals+(x.goals||0),assists:a.assists+(x.assists||0),xg:a.xg+(x.xg||0),xa:a.xa+(x.xa||0),chances:a.chances+(x.chances_created||0),key:a.key+(x.key_passes||0),tackles:a.tackles+(x.tackles||0),interceptions:a.interceptions+(x.interceptions||0),carries:a.carries+(x.progressive_carries||0)}),{minutes:0,appearances:0,goals:0,assists:0,xg:0,xa:0,chances:0,key:0,tackles:0,interceptions:0,carries:0});
const expiry=(d:string|null)=>d?new Date(d+"T00:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Unknown";
export default function ComparePage(){
 const[players,setPlayers]=useState<P[]>([]),[rows,setRows]=useState<I[]>([]),[contracts,setContracts]=useState<C[]>([]),[values,setValues]=useState<V[]>([]),[left,setLeft]=useState(""),[right,setRight]=useState(""),[season,setSeason]=useState("2026"),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const[p,i,c,v]=await Promise.all([supabase.from("players").select("id,full_name,nationality,position,photo_url").order("full_name"),supabase.from("player_season_intelligence").select("*"),supabase.from("contracts").select("player_id,annual_salary_usd,weekly_salary_usd,end_date,status"),supabase.from("market_values").select("player_id,market_value_usd,valuation_date").order("valuation_date",{ascending:false})]);setPlayers((p.data||[]) as P[]);setRows((i.data||[]) as I[]);setContracts((c.data||[]) as C[]);setValues((v.data||[]) as V[]);setLoading(false)})()},[]);
 const seasons=useMemo(()=>["All",...Array.from(new Set(rows.map(s=>s.season))).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}))],[rows]);
 const pick=(id:string)=>players.find(p=>p.id===id)||null;
 const stat=(id:string)=>sum(rows.filter(s=>s.player_id===id&&(season==="All"||s.season===season)));
 const contract=(id:string)=>contracts.find(c=>c.player_id===id&&c.status?.toLowerCase()==="active")||contracts.find(c=>c.player_id===id)||null;
 const value=(id:string)=>values.find(v=>v.player_id===id&&v.market_value_usd!=null)||null;
 const a=pick(left),b=pick(right),sa=left?stat(left):sum([]),sb=right?stat(right):sum([]),ca=left?contract(left):null,cb=right?contract(right):null,va=left?value(left):null,vb=right?value(right):null;
 const metric=(name:string,x:number|null,y:number|null)=><div className="compare-metric" key={name}><span>{name}</span><strong>{fmt(x)}</strong><strong>{fmt(y)}</strong></div>;
 const roleMetrics=[["Goals / 90",p90(sa.goals,sa.minutes),p90(sb.goals,sb.minutes)],["Assists / 90",p90(sa.assists,sa.minutes),p90(sb.assists,sb.minutes)],["xG / 90",p90(sa.xg,sa.minutes),p90(sb.xg,sb.minutes)],["xA / 90",p90(sa.xa,sa.minutes),p90(sb.xa,sb.minutes)],["Chances / 90",p90(sa.chances,sa.minutes),p90(sb.chances,sb.minutes)],["Key Passes / 90",p90(sa.key,sa.minutes),p90(sb.key,sb.minutes)],["Tackles / 90",p90(sa.tackles,sa.minutes),p90(sb.tackles,sb.minutes)],["Interceptions / 90",p90(sa.interceptions,sa.minutes),p90(sb.interceptions,sb.minutes)],["Progressive Carries / 90",p90(sa.carries,sa.minutes),p90(sb.carries,sb.minutes)]];
 return <main className="compare-page"><section className="compare-hero"><div><div>PLAYER INTELLIGENCE</div><h1>Compare Players</h1><p>Compare recorded performance, role metrics, league context, contracts, salaries and market values.</p></div></section><div className="compare-content"><div className="compare-controls"><label>Player 1<select value={left} onChange={e=>setLeft(e.target.value)}><option value="">Select player</option>{players.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label>Player 2<select value={right} onChange={e=>setRight(e.target.value)}><option value="">Select player</option>{players.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label>Season<select value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(s=><option key={s}>{s}</option>)}</select></label></div>{loading?<div className="compare-empty">Loading…</div>:<><div className="compare-player-grid"><Card p={a} v={va}/><Card p={b} v={vb}/></div>{(a||b)&&<><section className="compare-panel"><h2>Performance</h2><p>{season==="All"?"All recorded seasons":season}; values aggregate the database's recorded competitions.</p>{metric("Appearances",sa.appearances,sb.appearances)}{metric("Minutes",sa.minutes,sb.minutes)}{metric("Goals",sa.goals,sb.goals)}{metric("Assists",sa.assists,sb.assists)}{metric("xG",sa.xg,sb.xg)}{metric("xA",sa.xa,sb.xa)}{metric("Chances Created",sa.chances,sb.chances)}{metric("Key Passes",sa.key,sb.key)}{metric("Tackles",sa.tackles,sb.tackles)}{metric("Interceptions",sa.interceptions,sb.interceptions)}{metric("Progressive Carries",sa.carries,sb.carries)}</section><section className="compare-panel"><h2>Role Metrics · per 90</h2><p>Normalized by recorded minutes; descriptive measures, not ratings.</p>{roleMetrics.map(([n,x,y])=>metric(n as string,x as number|null,y as number|null))}</section><section className="compare-panel"><h2>Contract & Market Context</h2>{metric("Annual salary USD",ca?.annual_salary_usd??null,cb?.annual_salary_usd??null)}{metric("Weekly salary USD",ca?.weekly_salary_usd??null,cb?.weekly_salary_usd??null)}<div className="compare-metric"><span>Expiry</span><strong>{expiry(ca?.end_date??null)}</strong><strong>{expiry(cb?.end_date??null)}</strong></div>{metric("Market value",va?.market_value_usd??null,vb?.market_value_usd??null)}<div className="compare-metric"><span>Value date</span><strong>{va?.valuation_date||"—"}</strong><strong>{vb?.valuation_date||"—"}</strong></div></section></>}</>}</div></main>
}
function Card({p,v}:{p:P|null;v:V|null}){if(!p)return <div className="compare-player-card compare-placeholder">Select a player</div>;return <Link href={"/players/"+p.id} className="compare-player-card"><img src={p.photo_url||"/wfm-player-placeholder.svg"} alt="" style={{objectPosition:"50% 18%"}}/><div><strong>{p.full_name}</strong><span>{p.nationality||"Nationality unknown"} · {p.position||"Position unknown"}</span><small>{money(v?.market_value_usd??null)} market value</small></div></Link>}
