"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";
type P={id:string;full_name:string;nationality:string|null;position:string|null;photo_url:string|null};
type S={player_id:string;season:string;minutes:number|null;appearances:number|null;goals:number|null;assists:number|null;xg:number|null;xa:number|null;chances_created:number|null;key_passes:number|null;tackles:number|null;interceptions:number|null;progressive_carries:number|null};
type C={player_id:string;annual_salary_usd:number|null;weekly_salary_usd:number|null;end_date:string|null;status:string|null};
type V={player_id:string;market_value_usd:number|null;valuation_date:string|null};
const sum=(r:S[])=>r.reduce((a,x)=>({minutes:a.minutes+(x.minutes||0),appearances:a.appearances+(x.appearances||0),goals:a.goals+(x.goals||0),assists:a.assists+(x.assists||0),xg:a.xg+(x.xg||0),xa:a.xa+(x.xa||0),chances:a.chances+(x.chances_created||0),key:a.key+(x.key_passes||0),tackles:a.tackles+(x.tackles||0),interceptions:a.interceptions+(x.interceptions||0),carries:a.carries+(x.progressive_carries||0)}),{minutes:0,appearances:0,goals:0,assists:0,xg:0,xa:0,chances:0,key:0,tackles:0,interceptions:0,carries:0});
const p90=(v:number,m:number)=>m?v*90/m:null;
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const fmt=(v:number|null)=>v==null?"—":v.toLocaleString("en-US",{maximumFractionDigits:2});
export default function ComparePage(){
 const[players,setPlayers]=useState<P[]>([]),[stats,setStats]=useState<S[]>([]),[contracts,setContracts]=useState<C[]>([]),[values,setValues]=useState<V[]>([]),[left,setLeft]=useState(""),[right,setRight]=useState(""),[season,setSeason]=useState("2026"),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const[p,s,c,v]=await Promise.all([supabase.from("players").select("id,full_name,nationality,position,photo_url").order("full_name"),supabase.from("player_stats").select("player_id,season,minutes,appearances,goals,assists,xg,xa,chances_created,key_passes,tackles,interceptions,progressive_carries"),supabase.from("contracts").select("player_id,annual_salary_usd,weekly_salary_usd,end_date,status"),supabase.from("market_values").select("player_id,market_value_usd,valuation_date").order("valuation_date",{ascending:false})]);setPlayers((p.data||[]) as P[]);setStats((s.data||[]) as S[]);setContracts((c.data||[]) as C[]);setValues((v.data||[]) as V[]);setLoading(false)})()},[]);
 const seasons=useMemo(()=>["All",...Array.from(new Set(stats.map(s=>s.season))).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}))],[stats]);
 const pick=(id:string)=>players.find(p=>p.id===id)||null, rows=(id:string)=>sum(stats.filter(s=>s.player_id===id&&(season==="All"||s.season===season))), contract=(id:string)=>contracts.find(c=>c.player_id===id&&c.status?.toLowerCase()==="active")||contracts.find(c=>c.player_id===id)||null, value=(id:string)=>values.find(v=>v.player_id===id&&v.market_value_usd!=null)||null;
 const a=pick(left),b=pick(right),sa=left?rows(left):sum([]),sb=right?rows(right):sum([]),ca=left?contract(left):null,cb=right?contract(right):null,va=left?value(left):null,vb=right?value(right):null;
 const metric=(name:string,x:number|null,y:number|null)=><div className="compare-metric" key={name}><span>{name}</span><strong>{fmt(x)}</strong><strong>{fmt(y)}</strong></div>;
 return <main className="compare-page"><section className="compare-hero"><div><div>PLAYER INTELLIGENCE</div><h1>Compare Players</h1><p>Compare two WFM player records using the same performance, contract and market-value fields.</p></div></section><div className="compare-content"><div className="compare-controls"><label>Player 1<select value={left} onChange={e=>setLeft(e.target.value)}><option value="">Select player</option>{players.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label>Player 2<select value={right} onChange={e=>setRight(e.target.value)}><option value="">Select player</option>{players.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label>Season<select value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(s=><option key={s}>{s}</option>)}</select></label></div>{loading?<div className="compare-empty">Loading…</div>:<><div className="compare-player-grid"><Card p={a} v={va}/><Card p={b} v={vb}/></div>{(a||b)&&<><section className="compare-panel"><h2>Performance</h2><p>{season==="All"?"All recorded seasons":season}; per-90 uses recorded minutes.</p>{metric("Appearances",sa.appearances,sb.appearances)}{metric("Minutes",sa.minutes,sb.minutes)}{metric("Goals",sa.goals,sb.goals)}{metric("Assists",sa.assists,sb.assists)}{metric("xG",sa.xg,sb.xg)}{metric("xA",sa.xa,sb.xa)}{metric("Chances Created",sa.chances,sb.chances)}{metric("Key Passes",sa.key,sb.key)}{metric("Tackles",sa.tackles,sb.tackles)}{metric("Interceptions",sa.interceptions,sb.interceptions)}{metric("Progressive Carries",sa.carries,sb.carries)}{metric("Goals / 90",p90(sa.goals,sa.minutes),p90(sb.goals,sb.minutes))}{metric("Assists / 90",p90(sa.assists,sa.minutes),p90(sb.assists,sb.minutes))}</section><section className="compare-panel"><h2>Contract & Market</h2>{metric("Annual salary",ca?.annual_salary_usd??null,cb?.annual_salary_usd??null)}{metric("Weekly salary",ca?.weekly_salary_usd??null,cb?.weekly_salary_usd??null)}{metric("Market value",va?.market_value_usd??null,vb?.market_value_usd??null)}</section></>}</>}</div></main>
}
function Card({p,v}:{p:P|null;v:V|null}){if(!p)return <div className="compare-player-card compare-placeholder">Select a player</div>;return <Link href={"/players/"+p.id} className="compare-player-card"><img src={p.photo_url||"/wfm-player-placeholder.svg"} alt=""/><div><strong>{p.full_name}</strong><span>{p.nationality||"Nationality unknown"} · {p.position||"Position unknown"}</span><small>{money(v?.market_value_usd??null)} market value</small></div></Link>}
