'use client'
import { FormEvent,useEffect,useState } from 'react'
import Link from 'next/link'
import { supabase } from '../../lib/supabase'
type Product={id:string;code:string;name:string;description:string|null;license_type:string}
type Request={id:string;status:string;requested_term:string;intended_use:string;created_at:string;product:{name:string}|null}
type Agreement={id:string;agreement_reference:string;status:string;starts_at:string;ends_at:string|null;product:{name:string}|null}
export default function LicensingPage(){
 const [products,setProducts]=useState<Product[]>([]),[requests,setRequests]=useState<Request[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]),[product,setProduct]=useState(''),[term,setTerm]=useState('12_months'),[use,setUse]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setError('Please sign in to request commercial licensing.');setLoading(false);return}
 const [{data:p},{data:r},{data:a}]=await Promise.all([supabase.from('wfm_license_products').select('id,code,name,description,license_type').eq('active',true).order('name'),supabase.from('wfm_license_requests').select('id,status,requested_term,intended_use,created_at,product:wfm_license_products(name)').eq('requested_by',u.user.id).order('created_at',{ascending:false}),supabase.from('wfm_license_agreements').select('id,agreement_reference,status,starts_at,ends_at,product:wfm_license_products(name)').order('created_at',{ascending:false})]);setProducts((p||[]) as Product[]);setRequests((r||[]) as any);setAgreements((a||[]) as any);setLoading(false)}
 useEffect(()=>{void load()},[])
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!product||!use.trim())return;setBusy(true);setError('');setMessage('');const {error:e1}=await supabase.rpc('submit_license_request',{p_product_id:product,p_intended_use:use.trim(),p_requested_term:term,p_club_id:null,p_requested_scope:{}});if(e1)setError(e1.message);else{setUse('');setMessage('License request submitted to WFM.');await load()}setBusy(false)}
 if(loading)return <main className="account-page"><div className="account-card">Loading licensing workspace…</div></main>
 return <main className="account-page"><section className="account-card"><div className="account-card-top"><div><div className="eyebrow">COMMERCIAL · LICENSING</div><h1>WFM licensing</h1><p>Request professional scouting, commercial data, or API access. Access is governed by an executed WFM agreement.</p></div><Link href="/account/settings" className="outline">Account settings</Link></div>{error&&<div className="account-message account-error">{error}</div>}{message&&<div className="account-message account-success">{message}</div>}<div className="account-settings-grid"><form onSubmit={submit} className="settings-section"><div className="settings-section-heading"><span>REQUEST ACCESS</span><h2>License request</h2></div><label>Product<select value={product} onChange={e=>setProduct(e.target.value)} required><option value="">Select a license</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Term<select value={term} onChange={e=>setTerm(e.target.value)}><option value="12_months">12 months</option><option value="6_months">6 months</option><option value="custom">Custom</option></select></label><label>Intended use<textarea value={use} onChange={e=>setUse(e.target.value)} required maxLength={1200} rows={6} placeholder="Describe how WFM data will be used, by whom, and for what business purpose."/></label><button className="settings-primary" disabled={busy||!product}>{busy?'Submitting…':'Submit licensing request'}</button></form><section className="settings-section"><div className="settings-section-heading"><span>PRODUCTS</span><h2>Available licensing</h2></div>{products.map(p=><div key={p.id} className="account-membership-row"><div><strong>{p.name}</strong><small>{p.license_type} · {p.description||'WFM commercial access'}</small></div></div>)}</section></div><section className="settings-section" style={{marginTop:16}}><div className="settings-section-heading"><span>MY REQUESTS</span><h2>{requests.length} requests</h2></div>{requests.length?requests.map(r=><div className="account-membership-row" key={r.id}><div><strong>{r.product?.name||'License'}</strong><small>{r.requested_term} · {new Date(r.created_at).toLocaleDateString()} · {r.intended_use}</small></div><span className="account-status-pill">{r.status}</span></div>):<p className="account-muted">No licensing requests yet.</p>}</section><section className="settings-section" style={{marginTop:16}}><div className="settings-section-heading"><span>AGREEMENTS</span><h2>Active commercial agreements</h2></div>{agreements.length?agreements.map(a=><div className="account-membership-row" key={a.id}><div><strong>{a.product?.name||'WFM License'}</strong><small>{a.agreement_reference} · {new Date(a.starts_at).toLocaleDateString()}{a.ends_at?' – '+new Date(a.ends_at).toLocaleDateString():''}</small></div><span className="account-status-pill">{a.status}</span></div>):<p className="account-muted">No executed agreements.</p>}</section></section></main>
}
