"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "../../lib/supabase";
import { useWfmT } from '../../lib/use-wfm-t'

type Plan={id:string;code:string;name:string;description:string|null;monthly_price_usd:number|null;annual_price_usd:number|null;active:boolean;features:Record<string,boolean>};
type Entitlement={id:string;user_id:string|null;club_id:string|null;plan_code:string;status:string;starts_at:string;ends_at:string|null;source:string;external_reference:string|null};
type Activity={user_id:string|null;display_name:string|null;email:string|null;account_type:string|null;organization_name:string|null;job_title:string|null;event_type:string;path:string;metadata:Record<string,unknown>;occurred_at:string};

export default function CommercialAdminPage(){
 const t=useWfmT()
 const [authorized,setAuthorized]=useState(false);const [loading,setLoading]=useState(true);const [plans,setPlans]=useState<Plan[]>([]);const [entitlements,setEntitlements]=useState<Entitlement[]>([]);
 const [email,setEmail]=useState("");const [plan,setPlan]=useState("club");const [clubId,setClubId]=useState("");const [userId,setUserId]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [activity,setActivity]=useState<Activity[]>([]);
 const load=async()=>{const {data:u}=await supabase.auth.getUser();if(!u.user){setLoading(false);return}const {data:a}=await supabase.from("wfm_admins").select("user_id").eq("user_id",u.user.id).maybeSingle();setAuthorized(!!a);if(!a){setLoading(false);return}
 const [{data:p},{data:e},{data:activityRows}]=await Promise.all([supabase.from("wfm_access_plans").select("*").order("created_at"),supabase.from("wfm_account_entitlements").select("*").order("created_at",{ascending:false}),supabase.rpc("get_wfm_admin_visitor_activity",{p_limit:1000,p_since:new Date(Date.now()-7*24*60*60*1000).toISOString()})]);setPlans((p??[]) as Plan[]);setEntitlements((e??[]) as Entitlement[]);setActivity((activityRows??[]) as Activity[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const grant=async(ev:FormEvent)=>{ev.preventDefault();setBusy(true);setError("");setMessage("");if(!userId&&!clubId){setError("Enter a user ID or club ID.");setBusy(false);return}
 const {error:e}=await supabase.from("wfm_account_entitlements").insert({user_id:userId||null,club_id:clubId||null,plan_code:plan,source:"admin"});if(e)setError(e.message);else{setUserId("");setClubId("");setMessage("Entitlement assigned.");await load()}setBusy(false)};
 const accountUsage=useMemo(()=>{
  const map=new Map<string,{activity:Activity;events:number;pages:Set<string>;features:Map<string,number>;scouting:number}>()
  for(const row of activity){if(!row.user_id)continue;const existing=map.get(row.user_id);const target=existing??{activity:row,events:0,pages:new Set<string>(),features:new Map<string,number>(),scouting:0};target.events+=1;if(row.event_type==="page_view")target.pages.add(row.path);if(row.event_type==="interaction"){const action=typeof row.metadata?.action==="string"?row.metadata.action:"";if(action)target.features.set(action,(target.features.get(action)??0)+1);if(action.startsWith("scouting_"))target.scouting+=1}if(!existing)map.set(row.user_id,target)}
  return [...map.values()].sort((a,b)=>b.events-a.events).slice(0,10)
 },[activity])
 const accountTypes=useMemo(()=>{const counts=new Map<string,number>();for(const row of activity)if(row.user_id){const type=row.account_type||"unclassified";counts.set(type,(counts.get(type)??0)+1)}return [...counts.entries()].sort((a,b)=>b[1]-a[1])},[activity])
 const toggle=async(p:Plan)=>{const {error:e}=await supabase.from("wfm_access_plans").update({active:!p.active,updated_at:new Date().toISOString()}).eq("id",p.id);if(e)setError(e.message);else await load()};
 if(loading)return <main className="account-page"><div className="account-card">{t("Loading commercial dashboard…")}</div></main>;
 if(!authorized)return <main className="account-page"><div className="account-card"><div className="eyebrow">{t("ADMIN")}</div><h1>{t("Access restricted")}</h1><p className="account-muted">{t("This workspace is limited to WFM administrators.")}</p></div></main>;
 return <main className="account-page"><section className="account-card"><div className="account-card-top"><div><div className="eyebrow">{t("WFM ADMIN · COMMERCIAL")}</div><h1>{t("Commercial dashboard")}</h1><p>{t("Manage access plans and manually provision commercial entitlements. Billing-provider integration can be connected later without changing this access model.")}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/admin/club-access" className="outline">{t("Club access")}</Link><Link href="/admin/visitor-activity" className="outline">{t("Visitor activity")}</Link></div></div>
 {error&&<div className="account-message account-error">{error}</div>}{message&&<div className="account-message account-success">{message}</div>}
 <div className="club-workspace-grid"><section className="settings-section"><div className="settings-section-heading"><span>{t("PLANS")}</span><h2>{t("Access catalog")}</h2></div>{plans.map(p=><div key={p.id} className="account-membership-row"><div><strong>{p.name}</strong><small>{p.code} · {p.description||t("No description")}</small></div><button type="button" className="outline" onClick={()=>void toggle(p)}>{p.active?t("Active"):t("Inactive")}</button></div>)}</section>
 <section className="settings-section"><div className="settings-section-heading"><span>{t("PROVISION")}</span><h2>{t("Assign entitlement")}</h2></div><form onSubmit={grant}><label>{t("Plan")}<select value={plan} onChange={e=>setPlan(e.target.value)}>{plans.filter(p=>p.active).map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select></label><label>{t("User ID")}<input value={userId} onChange={e=>setUserId(e.target.value)} placeholder={t("Optional auth user UUID")} /></label><label>{t("Club ID")}<input value={clubId} onChange={e=>setClubId(e.target.value)} placeholder={t("Optional club UUID")} /></label><button className="settings-primary" disabled={busy} type="submit">{busy?t("Saving…"):t("Assign entitlement")}</button></form><p className="account-muted">{t("Only WFM admins can create or change entitlements. Keep payment processing outside this page until a billing provider is connected.")}</p></section></div>
 <div className="club-workspace-grid" style={{marginTop:24}}>
 <section className="settings-section"><div className="settings-section-heading"><span>{t("COMMERCIAL INTELLIGENCE")}</span><h2>{t("Account usage")}</h2></div><p className="account-muted">{t("Signed-in account activity from the last 7 days, grouped for commercial planning. Anonymous traffic is excluded.")}</p>{accountUsage.length===0?<p className="account-muted">{t("No signed-in account activity yet.")}</p>:<div style={{display:"grid",gap:10}}>{accountUsage.map(({activity:row,events,pages,features,scouting})=><div key={row.user_id} style={{border:"1px solid #e3e3e3",borderRadius:12,padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{row.organization_name||row.display_name||row.email||row.user_id?.slice(0,8)}</strong><small style={{display:"block"}}>{row.account_type||t("Unclassified account")}{row.job_title?" · "+row.job_title:""}</small></div><strong>{events} {t("events")}</strong></div><small>{pages.size} {t("unique pages")} · {scouting} {t("scouting actions")}</small><div style={{marginTop:8,display:"flex",gap:6,flexWrap:"wrap"}}>{[...features.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([feature,count])=><span key={feature} className="account-status-pill">{feature} · {count}</span>)}</div></div>)}</div>}</section>
 <section className="settings-section"><div className="settings-section-heading"><span>{t("ACCOUNT MIX")}</span><h2>{t("Usage by account type")}</h2></div>{accountTypes.length===0?<p className="account-muted">{t("No account activity yet.")}</p>:<div style={{display:"grid",gap:9}}>{accountTypes.map(([type,count])=><div key={type} style={{display:"flex",justifyContent:"space-between",gap:12}}><span>{type}</span><strong>{count} {t("events")}</strong></div>)}</div>}</section></div>
 <section className="settings-section" style={{marginTop:24}}><div className="settings-section-heading"><span>{t("ENTITLEMENTS")}</span><h2>{entitlements.length} {t("records")}</h2></div>{entitlements.length?entitlements.map(e=><div key={e.id} className="account-membership-row"><div><strong>{e.plan_code}</strong><small>{e.club_id?t("Club:")+" "+e.club_id:t("User:")+" "+e.user_id} · {e.status}</small></div><span className="account-status-pill">{e.source}</span></div>):<p className="account-muted">{t("No commercial entitlements have been assigned.")}</p>}</section>
 </section></main>
}
