"use client";

type Stat={season:string;minutes:number|null;goals:number|null;assists:number|null;xg:number|null;xa:number|null;chances_created:number|null;key_passes:number|null;tackles:number|null;interceptions:number|null;progressive_carries:number|null};
type Value={valuation_date:string|null;market_value_usd:number|null;confidence:string|null};
type Contract={status:string|null;start_date:string|null;end_date:string|null;annual_salary_usd:number|null;weekly_salary_usd:number|null;confidence:string|null;};
type SeasonIntel={season:string;club_name:string|null;league:string|null;position:string|null;minutes:number|null;goals:number|null;assists:number|null;goals_per90:number|null;assists_per90:number|null;xg_per90:number|null;xa_per90:number|null;chances_created_per90:number|null;key_passes_per90:number|null;tackles_per90:number|null;interceptions_per90:number|null;progressive_carries_per90:number|null;duels_won_per90:number|null};
type PeerBenchmark={season:string;league:string|null;position:string|null;peer_count:number|null;goals_per90_percentile:number|null;assists_per90_percentile:number|null;xg_per90_percentile:number|null;xa_per90_percentile:number|null;chances_created_per90_percentile:number|null;key_passes_per90_percentile:number|null;tackles_per90_percentile:number|null;interceptions_per90_percentile:number|null;progressive_carries_per90_percentile:number|null};
const n=(v:number|null)=>v||0;
const p90=(v:number,m:number)=>m?v*90/m:null;
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const fmt=(v:number|null)=>v==null?"—":v.toLocaleString("en-US",{maximumFractionDigits:2});
const agg=(r:Stat[])=>r.reduce((a,s)=>({minutes:a.minutes+n(s.minutes),goals:a.goals+n(s.goals),assists:a.assists+n(s.assists),xg:a.xg+n(s.xg),xa:a.xa+n(s.xa),chances:a.chances+n(s.chances_created),key:a.key+n(s.key_passes),tackles:a.tackles+n(s.tackles),interceptions:a.interceptions+n(s.interceptions),carries:a.carries+n(s.progressive_carries)}),{minutes:0,goals:0,assists:0,xg:0,xa:0,chances:0,key:0,tackles:0,interceptions:0,carries:0});
export default function PlayerIntelligence({stats,marketValues,position,contracts,seasonIntelligence,peerBenchmarks}:{stats:Stat[];marketValues:Value[];position:string|null;contracts:Contract[];seasonIntelligence:SeasonIntel[];peerBenchmarks:PeerBenchmark[]}){
 const seasons=Array.from(new Set(stats.map(s=>s.season))).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));
 const current=agg(stats.filter(s=>s.season===seasons[0])), previous=agg(stats.filter(s=>s.season===seasons[1]));
 const change=(a:number,b:number)=>b?((a-b)/b)*100:null;
 const latest=marketValues[0]?.market_value_usd??null, prior=marketValues[1]?.market_value_usd??null;
 const rows=seasons.slice(0,6).reverse().map(season=>({season,...agg(stats.filter(s=>s.season===season))}));
 const max=Math.max(1,...rows.map(r=>r.goals+r.assists));
 const metrics=[["Minutes",current.minutes,change(current.minutes,previous.minutes)],["Goals",current.goals,change(current.goals,previous.goals)],["Assists",current.assists,change(current.assists,previous.assists)],["xG",current.xg,change(current.xg,previous.xg)],["xA",current.xa,change(current.xa,previous.xa)],["Chances",current.chances,change(current.chances,previous.chances)]];
 const role=[["Goals / 90",p90(current.goals,current.minutes)],["Assists / 90",p90(current.assists,current.minutes)],["Key Passes / 90",p90(current.key,current.minutes)],["Tackles / 90",p90(current.tackles,current.minutes)],["Interceptions / 90",p90(current.interceptions,current.minutes)],["Progressive Carries / 90",p90(current.carries,current.minutes)]];
 const currentContract=contracts.find(c=>c.status?.toLowerCase()==="active")||contracts[0]||null;
 const latestIntel=seasonIntelligence[0]||null;
 const latestPeer=peerBenchmarks.find(p=>p.season===latestIntel?.season)||peerBenchmarks[0]||null;
 const percentile=(v:number|null)=>v==null?"—":String(Math.round(v))+"th";
 const valueChange=latest!=null&&prior!=null&&prior!==0?((latest-prior)/prior)*100:null;
 const contractDays=currentContract?.end_date?Math.ceil((new Date(`${currentContract.end_date}T00:00:00`).getTime()-Date.now())/86400000):null;
 const contextMetrics=latestIntel?[["Goals / 90",latestIntel.goals_per90,latestPeer?.goals_per90_percentile??null],["Assists / 90",latestIntel.assists_per90,latestPeer?.assists_per90_percentile??null],["Key Passes / 90",latestIntel.key_passes_per90,latestPeer?.key_passes_per90_percentile??null],["Tackles / 90",latestIntel.tackles_per90,latestPeer?.tackles_per90_percentile??null],["Interceptions / 90",latestIntel.interceptions_per90,latestPeer?.interceptions_per90_percentile??null],["Progressive Carries / 90",latestIntel.progressive_carries_per90,latestPeer?.progressive_carries_per90_percentile??null]]:[];
 return <section className="player-intelligence"><div className="intelligence-header"><div><h2>Performance Intelligence</h2><p>Season trends, per-90 output and recorded market-value movement.</p></div><a href="/compare">Compare players →</a></div>
 {!stats.length?<div className="intelligence-empty">Performance intelligence will appear as statistics are added.</div>:<><div className="intelligence-stat-grid">{metrics.map(([label,value,delta])=><div className="intelligence-stat" key={String(label)}><span>{label}</span><strong>{fmt(value as number)}</strong>{delta!=null&&<small className={Number(delta)>=0?"trend-up":"trend-down"}>{Number(delta)>=0?"↑":"↓"} {Math.abs(Number(delta)).toFixed(0)}% vs {seasons[1]}</small>}</div>)}</div>
 <div className="intelligence-panels"><div className="intelligence-panel"><b>Season Output</b><small>Goals + assists</small>{rows.map(r=><div className="intelligence-bar" key={r.season}><span>{r.season}</span><i><em style={{width:Math.max(4,((r.goals+r.assists)/max)*100)+"%"}}/></i><strong>{r.goals+r.assists}</strong></div>)}</div>
 <div className="intelligence-panel"><b>Role Metrics · per 90</b><small>Normalized by recorded minutes</small><div className="role-grid">{role.map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{fmt(value as number|null)}</strong></div>)}</div><p>Per-90 figures are descriptive production measures, not player ratings.</p></div>
 {latestIntel&&<div className="intelligence-panel"><b>League & Position Context</b><small>{latestIntel.league||"League unknown"} · {latestIntel.position||position||"Position unknown"} · {latestIntel.season}{latestPeer?.peer_count!=null?" · "+latestPeer.peer_count+" peers":""}</small><div className="role-grid">{contextMetrics.map(([label,value,rank])=><div key={String(label)}><span>{label}</span><strong>{fmt(value as number|null)}</strong><small>{latestPeer?percentile(rank as number|null):"Peer context unavailable"}</small></div>)}</div><p>Percentiles compare recorded per-90 output with the database peer group; they are context, not player ratings.</p></div>}
 <div className="intelligence-panel"><b>Season Intelligence Table</b><small>Database-derived season context</small><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760,fontSize:11}}><thead><tr>{["Season","Club","League","Min","G","A","G/90","A/90","xG/90","xA/90"].map(h=><th key={h} style={{textAlign:"left",padding:"7px 5px",borderBottom:"1px solid #ddd",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{seasonIntelligence.slice(0,6).map(s=><tr key={`${s.season}-${s.club_name}`}><td style={{padding:"7px 5px"}}>{s.season}</td><td style={{padding:"7px 5px"}}>{s.club_name||"—"}</td><td style={{padding:"7px 5px"}}>{s.league||"—"}</td><td style={{padding:"7px 5px"}}>{fmt(s.minutes)}</td><td style={{padding:"7px 5px"}}>{fmt(s.goals)}</td><td style={{padding:"7px 5px"}}>{fmt(s.assists)}</td><td style={{padding:"7px 5px"}}>{fmt(s.goals_per90)}</td><td style={{padding:"7px 5px"}}>{fmt(s.assists_per90)}</td><td style={{padding:"7px 5px"}}>{fmt(s.xg_per90)}</td><td style={{padding:"7px 5px"}}>{fmt(s.xa_per90)}</td></tr>)}</tbody></table></div><p>This table uses the recorded season-intelligence view; missing values remain unreported.</p></div><div className="intelligence-panel"><b>Market Value & Contract</b><small>Recorded financial context, not a forecast</small><div className="role-grid"><div><span>Market Value</span><strong>{money(latest)}</strong></div><div><span>Prior Value</span><strong>{money(prior)}</strong></div><div><span>Value Change</span><strong className={valueChange!=null&&valueChange<0?"trend-down":valueChange!=null?"trend-up":""}>{valueChange==null?"—":`${valueChange>=0?"↑":"↓"} ${Math.abs(valueChange).toFixed(1)}%`}</strong></div><div><span>Annual Salary</span><strong>{money(currentContract?.annual_salary_usd??null)}</strong></div><div><span>Weekly Salary</span><strong>{money(currentContract?.weekly_salary_usd??null)}</strong></div><div><span>Contract Expiry</span><strong>{currentContract?.end_date||"Unknown"}</strong></div></div><small>{contractDays!=null?(contractDays>=0?`${contractDays} days remaining`:`Expired ${Math.abs(contractDays)} days ago`):"Contract duration unknown"} · {currentContract?.confidence||"Contract confidence unknown"} · {marketValues[0]?.confidence||"Value confidence unknown"}</small></div></div></>}
 </section>;
}