"use client";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Stat={season:string;minutes:number|null;goals:number|null;assists:number|null;xg:number|null;xa:number|null;chances_created:number|null;key_passes:number|null;tackles:number|null;interceptions:number|null;progressive_carries:number|null;saves:number|null;shots_on_target_faced:number|null;goals_against:number|null;clean_sheets:number|null;penalty_kicks_saved:number|null;penalty_kicks_faced:number|null};
type Value={valuation_date:string|null;market_value_usd:number|null;confidence:string|null};
type Contract={status:string|null;start_date:string|null;end_date:string|null;annual_salary_usd:number|null;weekly_salary_usd:number|null;confidence:string|null};
type SeasonIntel={season:string;club_name:string|null;league:string|null;position:string|null;minutes:number|null;goals:number|null;assists:number|null;goals_per90:number|null;assists_per90:number|null;xg_per90:number|null;xa_per90:number|null;chances_created_per90:number|null;key_passes_per90:number|null;tackles_per90:number|null;interceptions_per90:number|null;progressive_carries_per90:number|null;duels_won_per90:number|null};
type PeerBenchmark={season:string;league:string|null;position:string|null;peer_count:number|null;goals_per90_percentile:number|null;assists_per90_percentile:number|null;xg_per90_percentile:number|null;xa_per90_percentile:number|null;chances_created_per90_percentile:number|null;key_passes_per90_percentile:number|null;tackles_per90_percentile:number|null;interceptions_per90_percentile:number|null;progressive_carries_per90_percentile:number|null};
type GKBenchmark={season:string;league:string|null;peer_count:number|null;saves_per90:number|null;shots_faced_per90:number|null;goals_against_per90:number|null;clean_sheets_per90:number|null;pk_saves_per90:number|null;saves_per90_percentile:number|null;shots_faced_per90_percentile:number|null;goals_against_per90_percentile:number|null;clean_sheets_per90_percentile:number|null;pk_saves_per90_percentile:number|null};
const n=(v:number|null)=>v||0;
const p90=(v:number,m:number)=>m?v*90/m:null;
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const fmt=(v:number|null)=>v==null?"—":v.toLocaleString("en-US",{maximumFractionDigits:2});
const agg=(r:Stat[])=>r.reduce((a,s)=>({minutes:a.minutes+n(s.minutes),goals:a.goals+n(s.goals),assists:a.assists+n(s.assists),xg:a.xg+n(s.xg),xa:a.xa+n(s.xa),chances:a.chances+n(s.chances_created),key:a.key+n(s.key_passes),tackles:a.tackles+n(s.tackles),interceptions:a.interceptions+n(s.interceptions),carries:a.carries+n(s.progressive_carries),saves:a.saves+n(s.saves),faced:a.faced+n(s.shots_on_target_faced),against:a.against+n(s.goals_against),clean:a.clean+n(s.clean_sheets),pkSaved:a.pkSaved+n(s.penalty_kicks_saved),pkFaced:a.pkFaced+n(s.penalty_kicks_faced)}),{minutes:0,goals:0,assists:0,xg:0,xa:0,chances:0,key:0,tackles:0,interceptions:0,carries:0,saves:0,faced:0,against:0,clean:0,pkSaved:0,pkFaced:0});

export default function PlayerIntelligence({stats,marketValues,position,contracts,seasonIntelligence,peerBenchmarks}:{stats:Stat[];marketValues:Value[];position:string|null;contracts:Contract[];seasonIntelligence:SeasonIntel[];peerBenchmarks:PeerBenchmark[]}){
 const pathname=usePathname();
 const playerId=pathname.split("/").filter(Boolean).pop()||"";
 const isGoalkeeper=/goalkeeper|goalie|\bGK\b/i.test(position||"");
 const [gkBenchmarks,setGkBenchmarks]=useState<GKBenchmark[]>([]);
 useEffect(()=>{if(!isGoalkeeper||!playerId)return;let cancelled=false;(async()=>{const {data}=await supabase.from("player_goalkeeper_benchmarks").select("season,league,peer_count,saves_per90,shots_faced_per90,goals_against_per90,clean_sheets_per90,pk_saves_per90,saves_per90_percentile,shots_faced_per90_percentile,goals_against_per90_percentile,clean_sheets_per90_percentile,pk_saves_per90_percentile").eq("player_id",playerId).order("season",{ascending:false});if(!cancelled&&data)setGkBenchmarks(data as GKBenchmark[])})();return()=>{cancelled=true}},[isGoalkeeper,playerId]);
 const seasons=Array.from(new Set(stats.map(s=>s.season))).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));
 const current=agg(stats.filter(s=>s.season===seasons[0])),previous=agg(stats.filter(s=>s.season===seasons[1]));
 const change=(a:number,b:number)=>b?((a-b)/b)*100:null;
 const history=marketValues.filter(v=>v.market_value_usd!=null).slice(0,8),latest=history[0]?.market_value_usd??null,prior=history[1]?.market_value_usd??null;
 const rows=seasons.slice(0,6).reverse().map(season=>({season,...agg(stats.filter(s=>s.season===season))}));
 const max=Math.max(1,...rows.map(r=>isGoalkeeper?r.clean:r.goals+r.assists));
 const valueMax=Math.max(1,...history.map(v=>v.market_value_usd||0));
 const currentContract=contracts.find(c=>c.status?.toLowerCase()==="active")||contracts[0]||null;
 const latestIntel=seasonIntelligence[0]||null,latestPeer=peerBenchmarks.find(p=>p.season===latestIntel?.season)||peerBenchmarks[0]||null,gkPeer=gkBenchmarks.find(p=>p.season===seasons[0])||gkBenchmarks[0]||null;
 const percentile=(v:number|null)=>v==null?"—":`${Math.round(v)}th`;
 const valueChange=latest!=null&&prior!=null&&prior!==0?((latest-prior)/prior)*100:null;
 const contractDays=currentContract?.end_date?Math.ceil((new Date(`${currentContract.end_date}T00:00:00`).getTime()-Date.now())/86400000):null;
 const [open,setOpen]=useState<Record<string,boolean>>({overview:true,season:true,role:true,context:false,table:false,finance:false,history:false});
 const toggle=(key:string)=>setOpen(v=>({...v,[key]:!v[key]}));
 const allOpen=Object.values(open).every(Boolean); const setAll=(value:boolean)=>setOpen({overview:value,season:value,role:value,context:value,table:value,finance:value,history:value});
 const Section=({id,title,subtitle,children}:{id:string;title:string;subtitle?:string;children:React.ReactNode})=><div className="intelligence-panel" style={{padding:0,overflow:"hidden"}}><button type="button" onClick={()=>toggle(id)} aria-expanded={open[id]} style={{width:"100%",display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,border:0,background:"transparent",padding:"18px 20px",textAlign:"left",cursor:"pointer",color:"inherit"}}><span><b style={{display:"block",fontSize:14}}>{title}</b>{subtitle&&<small style={{display:"block",marginTop:3,color:"#888"}}>{subtitle}</small>}</span><strong style={{fontSize:18,lineHeight:1,color:"#777"}}>{open[id]?"−":"+"}</strong></button>{open[id]&&<div style={{padding:"0 20px 20px"}}>{children}</div>}</div>;
 return <section className="player-intelligence"><div className="intelligence-header"><div><h2>Performance Intelligence</h2><p>{isGoalkeeper?"Goalkeeper-specific performance, peer context, season trends and financial context.":"Field-player performance, peer context, season trends and financial context."}</p></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><button type="button" onClick={()=>setAll(!allOpen)} style={{border:"1px solid #ddd",borderRadius:7,background:"#fff",padding:"7px 10px",fontSize:11,cursor:"pointer"}}>{allOpen?"Collapse all":"Expand all"}</button><a href="/compare">Compare players →</a></div></div>
 {!stats.length?<div className="intelligence-empty">Performance intelligence will appear as statistics are added.</div>:<div className="intelligence-panels">
 <Section id="overview" title={isGoalkeeper?"Goalkeeper Overview":"Performance Overview"} subtitle="Current-season totals and change vs the previous recorded season"><div className="intelligence-stat-grid">{(isGoalkeeper?[["Minutes",current.minutes,change(current.minutes,previous.minutes)],["Saves",current.saves,change(current.saves,previous.saves)],["Goals Against",current.against,change(current.against,previous.against)],["Clean Sheets",current.clean,change(current.clean,previous.clean)],["Shots Faced",current.faced,change(current.faced,previous.faced)],["PK Saves",current.pkSaved,change(current.pkSaved,previous.pkSaved)]]:[["Minutes",current.minutes,change(current.minutes,previous.minutes)],["Goals",current.goals,change(current.goals,previous.goals)],["Assists",current.assists,change(current.assists,previous.assists)],["xG",current.xg,change(current.xg,previous.xg)],["xA",current.xa,change(current.xa,previous.xa)],["Chances",current.chances,change(current.chances,previous.chances)]]).map(([label,value,delta])=><div className="intelligence-stat" key={String(label)}><span>{label}</span><strong>{fmt(value as number)}</strong>{delta!=null&&<small className={Number(delta)>=0?"trend-up":"trend-down"}>{Number(delta)>=0?"↑":"↓"} {Math.abs(Number(delta)).toFixed(0)}% vs {seasons[1]}</small>}</div>)}</div></Section>
 <Section id="season" title="Season Output" subtitle={isGoalkeeper?"Clean sheets by recorded season":"Goals + assists by recorded season"}>{rows.map(r=><div className="intelligence-bar" key={r.season}><span>{r.season}</span><i><em style={{width:Math.max(4,((isGoalkeeper?r.clean:r.goals+r.assists)/max)*100)+"%"}}/></i><strong>{isGoalkeeper?r.clean:r.goals+r.assists}</strong></div>)}</Section>
 <Section id="role" title={isGoalkeeper?"Goalkeeper Metrics · per 90":"Role Metrics · per 90"} subtitle="Normalized by recorded minutes"><div className="role-grid">{(isGoalkeeper?[["Saves / 90",p90(current.saves,current.minutes)],["Shots Faced / 90",p90(current.faced,current.minutes)],["Goals Against / 90",p90(current.against,current.minutes)],["Clean Sheets / 90",p90(current.clean,current.minutes)],["PK Saves / 90",p90(current.pkSaved,current.minutes)],["PK Faced / 90",p90(current.pkFaced,current.minutes)]]:[["Goals / 90",p90(current.goals,current.minutes)],["Assists / 90",p90(current.assists,current.minutes)],["Key Passes / 90",p90(current.key,current.minutes)],["Tackles / 90",p90(current.tackles,current.minutes)],["Interceptions / 90",p90(current.interceptions,current.minutes)],["Progressive Carries / 90",p90(current.carries,current.minutes)]]).map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{fmt(value as number|null)}</strong></div>)}</div><p>{isGoalkeeper?"Goalkeeper measures are isolated from field-player attacking and defensive metrics.":"Per-90 figures are descriptive production measures, not player ratings."}</p></Section>
 {latestIntel&&<Section id="context" title="League & Position Context" subtitle={`${latestIntel.league||"League unknown"} · ${latestIntel.position||position||"Position unknown"} · ${latestIntel.season}${(isGoalkeeper?gkPeer?.peer_count:latestPeer?.peer_count)!=null?" · "+(isGoalkeeper?gkPeer?.peer_count:latestPeer?.peer_count)+" peers":""}`}><div className="role-grid">{isGoalkeeper?(gkPeer?[["Saves / 90",gkPeer.saves_per90,gkPeer.saves_per90_percentile],["Shots Faced / 90",gkPeer.shots_faced_per90,gkPeer.shots_faced_per90_percentile],["Goals Against / 90",gkPeer.goals_against_per90,gkPeer.goals_against_per90_percentile],["Clean Sheets / 90",gkPeer.clean_sheets_per90,gkPeer.clean_sheets_per90_percentile],["PK Saves / 90",gkPeer.pk_saves_per90,gkPeer.pk_saves_per90_percentile]]:[["GK peer context",null,null]]):[["Goals / 90",latestIntel.goals_per90,latestPeer?.goals_per90_percentile??null],["Assists / 90",latestIntel.assists_per90,latestPeer?.assists_per90_percentile??null],["Key Passes / 90",latestIntel.key_passes_per90,latestPeer?.key_passes_per90_percentile??null],["Tackles / 90",latestIntel.tackles_per90,latestPeer?.tackles_per90_percentile??null],["Interceptions / 90",latestIntel.interceptions_per90,latestPeer?.interceptions_per90_percentile??null],["Progressive Carries / 90",latestIntel.progressive_carries_per90,latestPeer?.progressive_carries_per90_percentile??null]]).map(([label,value,rank])=><div key={String(label)}><span>{label}</span><strong>{fmt(value as number|null)}</strong>{(isGoalkeeper?gkPeer:latestPeer)&&<small>{percentile(rank as number|null)}</small>}</div>)}</div><p>{isGoalkeeper?"Goalkeepers are benchmarked only against goalkeeper records with sufficient minutes in the same league and season.":"Percentiles compare recorded per-90 output with the database peer group; they are context, not player ratings."}</p></Section>}
 <Section id="table" title="Season Intelligence Table" subtitle={isGoalkeeper?"Goalkeeper-specific season totals":"Database-derived field-player season context"}><div style={{overflowX:"auto"}}>{isGoalkeeper?<table style={{width:"100%",borderCollapse:"collapse",minWidth:620,fontSize:11}}><thead><tr>{["Season","Min","Saves","Faced","GA","CS","PK Saves","PK Faced"].map(h=><th key={h} style={{textAlign:"left",padding:"7px 5px",borderBottom:"1px solid #ddd",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.season}>{[s.season,s.minutes,s.saves,s.faced,s.against,s.clean,s.pkSaved,s.pkFaced].map((v,i)=><td key={i} style={{padding:"7px 5px"}}>{i===0?v:fmt(v as number|null)}</td>)}</tr>)}</tbody></table>:<table style={{width:"100%",borderCollapse:"collapse",minWidth:760,fontSize:11}}><thead><tr>{["Season","Club","League","Min","G","A","G/90","A/90","xG/90","xA/90"].map(h=><th key={h} style={{textAlign:"left",padding:"7px 5px",borderBottom:"1px solid #ddd",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{seasonIntelligence.slice(0,6).map(s=><tr key={`${s.season}-${s.club_name}`}><td style={{padding:"7px 5px"}}>{s.season}</td><td style={{padding:"7px 5px"}}>{s.club_name||"—"}</td><td style={{padding:"7px 5px"}}>{s.league||"—"}</td><td style={{padding:"7px 5px"}}>{fmt(s.minutes)}</td><td style={{padding:"7px 5px"}}>{fmt(s.goals)}</td><td style={{padding:"7px 5px"}}>{fmt(s.assists)}</td><td style={{padding:"7px 5px"}}>{fmt(s.goals_per90)}</td><td style={{padding:"7px 5px"}}>{fmt(s.assists_per90)}</td><td style={{padding:"7px 5px"}}>{fmt(s.xg_per90)}</td><td style={{padding:"7px 5px"}}>{fmt(s.xa_per90)}</td></tr>)}</tbody></table>}</div><p>{isGoalkeeper?"Goalkeeper fields are kept separate from field-player attacking metrics.":"This table uses the recorded season-intelligence view; missing values remain unreported."}</p></Section>
 <Section id="finance" title="Market Value & Contract" subtitle="Recorded financial context, not a forecast"><div className="role-grid"><div><span>Market Value</span><strong>{money(latest)}</strong></div><div><span>Prior Value</span><strong>{money(prior)}</strong></div><div><span>Value Change</span><strong className={valueChange!=null&&valueChange<0?"trend-down":valueChange!=null?"trend-up":""}>{valueChange==null?"—":`${valueChange>=0?"↑":"↓"} ${Math.abs(valueChange).toFixed(1)}%`}</strong></div><div><span>Annual Salary</span><strong>{money(currentContract?.annual_salary_usd??null)}</strong></div><div><span>Weekly Salary</span><strong>{money(currentContract?.weekly_salary_usd??null)}</strong></div><div><span>Contract Expiry</span><strong>{currentContract?.end_date||"Unknown"}</strong></div></div><small>{contractDays!=null?(contractDays>=0?`${contractDays} days remaining`:`Expired ${Math.abs(contractDays)} days ago`):"Contract duration unknown"} · {currentContract?.confidence||"Contract confidence unknown"} · {marketValues[0]?.confidence||"Value confidence unknown"}</small></Section>
 {history.length>0&&<Section id="history" title="Market Value History" subtitle="Recorded valuation snapshots · newest first"><div style={{display:"grid",gap:8,marginTop:2}}>{history.map((v,i)=><div key={`${v.valuation_date}-${i}`} style={{display:"grid",gridTemplateColumns:"92px minmax(70px,1fr) 88px",gap:10,alignItems:"center"}}><span style={{fontSize:11,color:"#777"}}>{v.valuation_date||"Unknown"}</span><i style={{display:"block",height:10,background:"#e7e5dd",borderRadius:99,overflow:"hidden"}}><em style={{display:"block",height:"100%",width:Math.max(3,((v.market_value_usd||0)/valueMax)*100)+"%",background:"#111"}}/></i><strong style={{fontSize:12,textAlign:"right"}}>{money(v.market_value_usd)}</strong></div>)}</div><p>History reflects recorded valuations only; it does not predict future value.</p></Section>}
 </div>}
 </section>;
}
