'use client'
import { useEffect,useState } from 'react'
import { supabase } from '../../lib/supabase'
import { useWfmT } from '../../lib/use-wfm-t'
type Req={id:string;status:string;requested_term:string;intended_use:string;created_at:string;requested_by:string;club_id:string|null;product:{id:string;name:string;code:string}|null}
export default function LicensingAdmin(){
 const t=useWfmT()
 const [allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[rows,setRows]=useState<Req[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState<string|null>(null)
 const load=async()=>{setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setLoading(false);return}const {data:a}=await supabase.from('wfm_admins').select('user_id').eq('user_id',u.user.id).maybeSingle();if(!a){setError('WFM admin access required.');setLoading(false);return}setAllowed(true);const {data,error:e}=await supabase.from('wfm_license_requests').select('id,status,requested_term,intended_use,created_at,requested_by,club_id,product:wfm_license_products(id,name,code)').in('status',['pending','under_review','approved']).order('created_at',{ascending:true});if(e)setError(e.message);setRows((data||[]) as any);setLoading(false)}
 useEffect(()=>{void load()},[])
 const review=async(id:string,action:'under_review'|'approved'|'rejected')=>{setBusy(id);setError('');const {error:e}=await supabase.rpc('review_license_request',{p_request_id:id,p_action:action,p_admin_notes:null});if(e)setError(e.message);else{setNotice('Request marked '+action+'.');await load()}setBusy(null)}
 if(loading)return <main className="account-page"><div className="account-card">{t("Loading licensing administration…")}</div></main>
 if(!allowed)return <main className="account-page"><section className="account-card"><div className="eyebrow">{t("ADMIN")}</div><h1>{t("Licensing")}</h1><p className="account-muted">{error||'Admin access required.'}</p></section></main>
 return <main className="account-page"><section className="account-card"><div className="account-card-top"><div><div className="eyebrow">{t("WFM ADMIN · COMMERCIAL")}</div><h1>{t("Licensing requests")}</h1><p>{t("Review commercial access requests before issuing an executed agreement.")}</p></div><a href="/admin/commercial" className="outline">{t("Commercial access")}</a></div>{error&&<div className="account-message account-error">{error}</div>}{notice&&<div className="account-message account-success">{notice}</div>}{rows.length?<div className="club-board-list">{rows.map(r=><div className="club-board-card" key={r.id}><div><strong>{r.product?.name||'License request'}</strong><small>{r.requested_term} · {new Date(r.created_at).toLocaleDateString()} · requester {r.requested_by}</small><small>{r.intended_use}</small></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{r.status==='pending'&&<button className="outline" disabled={busy===r.id} onClick={()=>void review(r.id,'under_review')}>{t("Review")}</button>}{r.status!=='approved'&&<button className="outline" disabled={busy===r.id} onClick={()=>void review(r.id,'approved')}>{t("Approve")}</button>}{r.status!=='rejected'&&<button className="outline" disabled={busy===r.id} onClick={()=>void review(r.id,'rejected')}>{t("Reject")}</button>}</div></div>)}</div>:<p className="account-muted">{t("No active licensing requests.")}</p>}<section className="settings-section" style={{marginTop:20}}><div className="settings-section-heading"><span>{t("AGREEMENTS")}</span><h2>{t("Issuance")}</h2></div><p className="account-muted">An approved request must receive an agreement reference and executed commercial terms through the WFM agreement workflow before licensed access is considered active.</p></section></section></main>
}
